truncate table demonstracoes_contabeis;
drop table temp_demonstracoes;

CREATE TEMPORARY TABLE temp_demonstracoes (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
data_reg DATE,
REG_ANS INTEGER NOT NULL,
CD_CONTA_CONTABIL INTEGER NOT NULL,
DESCRICAO VARCHAR(255),
VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
)default CHARSET = utf8mb4;

LOAD DATA INFILE  'C:/wamp64/tmp/demonstracoes/2023/1T2023.csv'
INTO TABLE temp_demonstracoes
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SET data_reg = STR_TO_DATE(NULLIF(REPLACE(@DATA, '/', '-'), ''), '%Y-%m-%d');

INSERT INTO demonstracoes_contabeis (data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL
FROM temp_demonstracoes
WHERE CHAR_LENGTH(CD_CONTA_CONTABIL) = 9;
drop table temp_demonstracoes;

CREATE TEMPORARY TABLE temp_demonstracoes (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
data_reg DATE,
REG_ANS INTEGER NOT NULL,
CD_CONTA_CONTABIL INTEGER NOT NULL,
DESCRICAO VARCHAR(255),
VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
)default CHARSET = utf8mb4;

LOAD DATA INFILE  'C:/wamp64/tmp/demonstracoes/2023/2T2023.csv'
INTO TABLE temp_demonstracoes
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SET data_reg = STR_TO_DATE(NULLIF(REPLACE(@DATA, '/', '-'), ''), '%Y-%m-%d');

INSERT INTO demonstracoes_contabeis (data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL
FROM temp_demonstracoes
WHERE CHAR_LENGTH(CD_CONTA_CONTABIL) = 9;
drop table temp_demonstracoes;

CREATE TEMPORARY TABLE temp_demonstracoes (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
data_reg DATE,
REG_ANS INTEGER NOT NULL,
CD_CONTA_CONTABIL INTEGER NOT NULL,
DESCRICAO VARCHAR(255),
VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
)default CHARSET = utf8mb4;

LOAD DATA INFILE  'C:/wamp64/tmp/demonstracoes/2023/3T2023.csv'
INTO TABLE temp_demonstracoes
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SET data_reg = STR_TO_DATE(NULLIF(REPLACE(@DATA, '/', '-'), ''), '%Y-%m-%d');

INSERT INTO demonstracoes_contabeis (data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL
FROM temp_demonstracoes
WHERE CHAR_LENGTH(CD_CONTA_CONTABIL) = 9;
drop table temp_demonstracoes;

CREATE TEMPORARY TABLE temp_demonstracoes (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
data_reg DATE,
REG_ANS INTEGER NOT NULL,
CD_CONTA_CONTABIL INTEGER NOT NULL,
DESCRICAO VARCHAR(255),
VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
)default CHARSET = utf8mb4;

LOAD DATA INFILE  'C:/wamp64/tmp/demonstracoes/2023/4T2023.csv'
INTO TABLE temp_demonstracoes
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SET data_reg = STR_TO_DATE(NULLIF(REPLACE(@DATA, '/', '-'), ''), '%d-%m-%Y');

INSERT INTO demonstracoes_contabeis (data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL
FROM temp_demonstracoes
WHERE CHAR_LENGTH(CD_CONTA_CONTABIL) = 9;
drop table temp_demonstracoes;

CREATE TEMPORARY TABLE temp_demonstracoes (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
data_reg DATE,
REG_ANS INTEGER NOT NULL,
CD_CONTA_CONTABIL INTEGER NOT NULL,
DESCRICAO VARCHAR(255),
VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
)default CHARSET = utf8mb4;

LOAD DATA INFILE  'C:/wamp64/tmp/demonstracoes/2024/1T2024.csv'
INTO TABLE temp_demonstracoes
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SET data_reg = STR_TO_DATE(NULLIF(REPLACE(@DATA, '/', '-'), ''), '%Y-%m-%d');

INSERT INTO demonstracoes_contabeis (data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL
FROM temp_demonstracoes
WHERE CHAR_LENGTH(CD_CONTA_CONTABIL) = 9;
drop table temp_demonstracoes;

CREATE TEMPORARY TABLE temp_demonstracoes (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
data_reg DATE,
REG_ANS INTEGER NOT NULL,
CD_CONTA_CONTABIL INTEGER NOT NULL,
DESCRICAO VARCHAR(255),
VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
)default CHARSET = utf8mb4;

LOAD DATA INFILE  'C:/wamp64/tmp/demonstracoes/2024/2T2024.csv'
INTO TABLE temp_demonstracoes
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SET data_reg = STR_TO_DATE(NULLIF(REPLACE(@DATA, '/', '-'), ''), '%Y-%m-%d');

INSERT INTO demonstracoes_contabeis (data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL
FROM temp_demonstracoes
WHERE CHAR_LENGTH(CD_CONTA_CONTABIL) = 9;
drop table temp_demonstracoes;

CREATE TEMPORARY TABLE temp_demonstracoes (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
data_reg DATE,
REG_ANS INTEGER NOT NULL,
CD_CONTA_CONTABIL INTEGER NOT NULL,
DESCRICAO VARCHAR(255),
VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
)default CHARSET = utf8mb4;


LOAD DATA INFILE  'C:/wamp64/tmp/demonstracoes/2024/3T2024.csv'
INTO TABLE temp_demonstracoes
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SET data_reg = STR_TO_DATE(NULLIF(REPLACE(@DATA, '/', '-'), ''), '%Y-%m-%d');

INSERT INTO demonstracoes_contabeis (data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL
FROM temp_demonstracoes
WHERE CHAR_LENGTH(CD_CONTA_CONTABIL) = 9;
drop table temp_demonstracoes;

CREATE TEMPORARY TABLE temp_demonstracoes (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
data_reg DATE,
REG_ANS INTEGER NOT NULL,
CD_CONTA_CONTABIL INTEGER NOT NULL,
DESCRICAO VARCHAR(255),
VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
)default CHARSET = utf8mb4;


LOAD DATA INFILE  'C:/wamp64/tmp/demonstracoes/2024/4T2024.csv'
INTO TABLE temp_demonstracoes
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SET data_reg = STR_TO_DATE(NULLIF(REPLACE(@DATA, '/', '-'), ''), '%Y-%m-%d');

INSERT INTO demonstracoes_contabeis (data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT data_reg, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL
FROM temp_demonstracoes
WHERE CHAR_LENGTH(CD_CONTA_CONTABIL) = 9;
drop table temp_demonstracoes;
